name: PaulWalker
description: PaulWalker Blog
markdown: redcarpet
pygments: true
permalink: none
port: 4001
excerpt_separator: <!--more-->
redcarpet:
        extensions:
                - fenced_code_blocks
                - no_intra_emphasis
                - strikethrough
                - autolink
                - tables
