name: PaulWalker
description: PaulWalker Blog
permalink: none
port: 4001
excerpt_separator: <!--more-->
markdown: redcarpet
redcarpet:
        extensions: ["fenced_code_blocks", "tables" , "no_intra_emphasis" , "autolink", "with_toc_data"]
